### ISSUE TITLE
Bugfix: Fix R CMD CHECK Issues

### ISSUE THREAD

**Issue by jimbrig** [jimbrig/lossrx#37]
## Tasks:

- [ ] Attempt to reduce dependencies down from 24
- [x] Remove `.env` file in `spawnctl` inst dir
- [ ] Reduce size of `data` and `doc` directories
- [x] Fix globals:
    - [x] view_claim_history: no visible binding for global variable 'claims_transactional'
    - [x] view_claim_history: no visible global function definition for 'case_when'
    - [x] view_claim_history: no visible binding for global variable 'Transaction ID'
    - [x] view_claim_history: no visible binding for global variable 'Paid Change'
    - [x] view_claim_history: no visible binding for global variable 'Case Reserve Change'
    - [x] view_claim_history: no visible binding for global variable 'Reported Change'
    - [x] view_claim_history: no visible binding for global variable 'Status Details'
    - [x] view_claim_history: no visible binding for global variable 'Status'
    - [x] view_claim_history: no visible binding for global variable 'Transaction Details'
    - [x] view_claim_history: no visible binding for global variable 'Transaction Date'

## Output:

```
-- R CMD check results ----------------------------------------------- lossrx 0.0.2 ----
Duration: 1m 38.2s

> checking package dependencies ... NOTE
  Imports includes 24 non-default packages.
  Importing from so many packages makes the package vulnerable to any of
  them becoming unavailable.  Move as many as possible to Suggests and
  use conditionally.

> checking for hidden files and directories ... NOTE
  Found the following hidden files and directories:
    inst/spawnctl/.env
  These were most likely included in error. See section 'Package
  structure' in the 'Writing R Extensions' manual.

> checking installed package size ... NOTE
    installed size is  5.4Mb
    sub-directories of 1Mb or more:
      data   2.0Mb
      doc    2.5Mb

> checking R code for possible problems ... NOTE
  view_claim_history: no visible binding for global variable
    'claims_transactional'
  view_claim_history: no visible global function definition for
    'case_when'
  view_claim_history: no visible binding for global variable 'Transaction
    ID'
  view_claim_history: no visible binding for global variable 'Paid
    Change'
  view_claim_history: no visible binding for global variable 'Case
    Reserve Change'
  view_claim_history: no visible binding for global variable 'Reported
    Change'
  view_claim_history: no visible binding for global variable 'Status
    Details'
  view_claim_history: no visible binding for global variable 'Status'
  view_claim_history: no visible binding for global variable 'Transaction
    Details'
  view_claim_history: no visible binding for global variable 'Transaction
    Date'
  Undefined global functions or variables:
    Case Reserve Change Paid Change Reported Change Status Status Details
    Transaction Date Transaction Details Transaction ID case_when
    claims_transactional
```

**Comment by jimbrig** [comment]
Closing with issues remaining:

```
-- R CMD check results ----------------------------------------------- lossrx 0.0.2 ----
Duration: 1m 29.7s

> checking package dependencies ... NOTE
  Imports includes 24 non-default packages.
  Importing from so many packages makes the package vulnerable to any of
  them becoming unavailable.  Move as many as possible to Suggests and
  use conditionally.

> checking installed package size ... NOTE
    installed size is  5.5Mb
    sub-directories of 1Mb or more:
      data   2.0Mb
      doc    2.5Mb

0 errors v | 0 warnings v | 2 notes x

R CMD check succeeded
```
